### ISSUE TITLE
fix file name in google colab when downloading from civitai.com

### ISSUE THREAD

**Issue by x-legion** [aka7774/sd_filer#1]
![image](https://user-images.githubusercontent.com/97628039/216668667-04856214-7267-41eb-b2ef-2629ed356716.png)
the file saves as numbers like the civitai link. It doesn't pickup the new name from redirected URL.

**Comment by aka7774** [comment]
![image](https://user-images.githubusercontent.com/116415100/216772044-772a0339-361f-4f0a-ad39-188498b3b5bd.png)

Thank you!

**Comment by x-legion** [comment]
![image](https://user-images.githubusercontent.com/97628039/216775278-ab6148c7-1117-4f14-8452-dca6a39d3a75.png)
when downloading lora from civitiai in lora tab

**Comment by x-legion** [comment]
file path name mistake change lora to Lora might fix this

**Comment by x-legion** [comment]
also can you add multiple connections per download to speed the download.

**Comment by aka7774** [comment]
> file path name mistake change lora to Lora might fix this

The directory name was different between sd_dreambooth_extension and the original implementation. I've decided to match it to the original. It also supports --lora-dir.

**Comment by aka7774** [comment]
> also can you add multiple connections per download to speed the download.

I'd love to use aria2c or aria2p but I'll hold out because I'll need binaries for windows.

**Comment by x-legion** [comment]
> > file path name mistake change lora to Lora might fix this
> 
> The directory name was different between sd_dreambooth_extension and the original implementation. I've decided to match it to the original. It also supports --lora-dir.

https://github.com/ddPn08/kohya-sd-scripts-webui.git I use this one.

**Comment by x-legion** [comment]
> > also can you add multiple connections per download to speed the download.
> 
> I'd love to use aria2c or aria2p but I'll hold out because I'll need binaries for windows.

it takes at least a minute to download a model compared to 10s download with aria2c multiple connections

**Comment by aka7774** [comment]
> https://github.com/ddPn08/kohya-sd-scripts-webui.git I use this one.

It's a nice, simple tool.
It's made by high school kids.

**Comment by aka7774** [comment]
> it takes at least a minute to download a model compared to 10s download with aria2c multiple connections

My sweet Aria.
(on Colab)

```
aria_url = ''#@param {type:"string"}
if aria_url:
    !apt install -y -qq aria2
    !aria2c --summary-interval=10 -x 3 --allow-overwrite=true -Z {aria_url}
```
