### ISSUE TITLE
file name error model.safetensors"; 

### ISSUE THREAD

**Issue by x-legion** [aka7774/sd_filer#2]
![image](https://user-images.githubusercontent.com/97628039/217251274-2a6a0071-f1fa-46cf-b52f-b20efd2d8f54.png)

**Comment by aka7774** [comment]
Thanks! I fixed it.
https://github.com/aka7774/sd_filer/commit/6b619d667f19c4372b5c6b3a92580e8553be0b48これでも

If this doesn't work, I need the URL.
